### ISSUE TITLE
A little help please

### ISSUE THREAD

**Issue by mai-winter** [duncanheron/dropPin#4]
hi!
I am currently doing a project that uses map and pins. I saw your codes and I want to ask you about the drop pins. The user is able to click on the map to drop the pin right? So, do you know how I can make the coordinates appear on a text box?
For example, I have a form with x and y coordinates box. i want the coordinates to appear on the text box when the user clicks on a certain spot on the map. Do you know how or if I can achieve this outcome?

**Comment by coffeeshopcoder** [comment]
Hello, I'm not the author of this useful plugin, but I think I can offer some tips.

Among the options you can pass into the init method, there are:
````
hiddenXid: '#xcoord', //used for saving to db via hidden form field
hiddenYid: '#ycoord', //used for saving to db via hidden form field
````

I supposed you can bind the ids of a `<input type="text" />` rather than a `<input type="hidden" />` here. If not, you can bind the ids of hidden fields, and then read the values updated in those fields whenever a user clicks on your map.

Good luck!

**Comment by mai-winter** [comment]
oh wow thanks! I'll try and hope it works!

**Comment by duncanheron** [comment]
Did you get this working?
coffeeshopcoder's suggestion is probably the right direction. 

I would probably add the textboxes to your html and then in the plugin add a line similar to:
$('.yourtextbox').val(x) similar to how I have used the hidden input fields.

**Comment by mai-winter** [comment]
i tried the codes and it works.. thanks so much for ur help!
