### ISSUE TITLE
i wanna add new pin from the show pin window.

### ISSUE THREAD

**Issue by anujsharma2511** [duncanheron/dropPin#8]
i wanna add new pin from the show pin window.

what should i do?
thanks

**Comment by coffeeshopcoder** [comment]
@anujsharma2511 Please elaborate a bit more what you seek to accomplish, and how it is a relevant issue to the plugin codebase. I'm not the maintainer of this repository but I'll see how I can help you out if you provide more information.

Also, I'm guessing you would have better luck somewhere like [stackoverflow](http://stackoverflow.com/) if your issue is not directly related to the implementation of this plugin or falls outside of the scope of features.
